{% set name = "overturemaps" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/overturemaps-{{ version }}.tar.gz
  sha256: 52d612e4570d053f48222c9b2945cafa3c069d743ea11fc7408de7b5f57c3588

build:
  entry_points:
    - overturemaps = overturemaps.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - click >=8.1.7
    - numpy >=1.26.4
    - pyarrow >=15.0.2
    - shapely >=2.0.3

test:
  imports:
    - overturemaps
  commands:
    - pip check
    - overturemaps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OvertureMaps/overturemaps-py
  summary: Python tools for interacting with Overture Maps (overturemaps.org) data.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.overturemaps.org
  dev_url: https://github.com/OvertureMaps/overturemaps-py

extra:
  recipe-maintainers:
    - owenlamont
