{% set name = "overturemaps" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/overturemaps-{{ version }}.tar.gz
  sha256: beac618c6f2d6955b060da30173f76655f5f269d38566fc19be1fe9d328c32fc

build:
  entry_points:
    - overturemaps = overturemaps.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - click >=8.1.7,<9.0.0
    - numpy >=1.16.6,<2
    - pyarrow >=15.0.2,<16.0.0
    - shapely >=2.0.3,<3.0.0

test:
  imports:
    - overturemaps
  commands:
    - pip check
    - overturemaps --help
  requires:
    - pip

about:
  home: https://github.com/OvertureMaps/overturemaps-py
  summary: Python tools for interacting with Overture Maps (overturemaps.org) data.
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.overturemaps.org
  dev_url: https://github.com/OvertureMaps/overturemaps-py

extra:
  recipe-maintainers:
    - owenlamont
